
name: Nightly - Assign Milestones

on:
  schedule:
    # Runs daily at 09:00 UTC
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  assign-milestones:
    runs-on: windows-latest
    permissions:
      contents: write
      issues: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install GitHub CLI
        run: choco install gh -y

      - name: Verify gh auth
        run: |
          gh --version
          gh auth status || echo "Using GITHUB_TOKEN via GH_TOKEN env"

      - name: Verify scripts exist
        shell: pwsh
        run: |
          if (-Not (Test-Path "assign_milestones.py")) {
            Write-Error "assign_milestones.py missing"
            exit 1
          }

      - name: Run milestone assignment
        run: python assign_milestones.py
