name: Test Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Install package
        run: |
          pip install dist/*.whl

      - name: Run self-test
        run: |
          echo "__file__ = 'src/securecrypto_bridge/securecrypto.py'" > temp_selftest.py
          cat src/securecrypto_bridge/securecrypto.py >> temp_selftest.py
          python temp_selftest.py
