
name: CI - Python self-test

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test-windows:
    runs-on: windows-latest
    env:
      PYTHONIOENCODING: utf-8
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pythonnet
          pip install -e .

      - name: Verify package layout
        shell: pwsh
        run: |
          if (-Not (Test-Path "src/securecrypto_bridge/securecrypto.py")) { Write-Error "securecrypto.py not in src layout"; exit 1 }
          if (-Not (Test-Path "src/securecrypto_bridge/SecureCrypto.dll")) { Write-Error "SecureCrypto.dll missing under src/securecrypto_bridge"; exit 1 }

      - name: Run self-test
        run: python -c "import securecrypto_bridge as sc; import importlib; importlib.reload(sc); exec(open('src/securecrypto_bridge/securecrypto.py','r',encoding='utf-8').read())"

      - name: Run examples
        run: |
          python examples/aes_example.py
          python examples/rsa_hybrid_example.py
          python examples/sign_verify_example.py
